# SonarCloud
sonar.organization=cyprientemateu
sonar.projectKey=cyprientemateu_cyprien-ecommerce-project
sonar.projectName=cyprien-ecommerce-project
sonar.projectVersion=1.0
sonar.sources=./do-it-yourself
qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.java.binaries=do-it-yourself/src/ui/target/classes,do-it-yourself/src/cart/target/classes,do-it-yourself/src/orders/target/classes